URL = "https://store.steampowered.com/"
Driver_Path = r"C:\Users\Aboudi\PycharmProjects\SeleniumDrivers\chromedriver.exe"
ABOUT_XPath = "(//div[@class='supernav_container']//child::a[@class='menuitem'])[1]"
Online_gamers_XPath = "//div[contains(@class, 'gamers_online')]//parent::div[@class='online_stat']"
gamers_in_game_XPath = "//div[contains(@class, 'gamers_in_game')]//parent::div[@class='online_stat']"
store_XPath = "//div[@id='global_header']//child::a[contains(@data-tooltip-content, 'store')]"
New_and_Noteworthy_XPath = "//div[@id='noteworthy_tab']"
Top_sellers_XPath = "//a[@class='popup_menu_item' and contains(text(),'Top Sellers')]"
OSs_XPath = "//div[@data-collapse-name='os']"
needed_OS_XPath = "//div[@data-value='linux']"
number_of_players_area_XPath = "//div[@data-collapse-name='category3']"
LAN_XPath = "//div[@data-value='48']"
first_see_all_XPath = "(//a[@class='see_all_expander'])[1]"
tag_area_XPath = "//div[@data-collapse-name='tags']"
action_XPath = "//span[@data-value='19' and @data-param='tags']"
action_count_XPath = "//span[@data-value='19' and @data-param='tags']//span//span[contains(@class,'count')]"
URL_of_choosing_LAN_and_linux = "https://store.steampowered.com/search/?category3=48&os=linux&filter=topsellers"
search_results_count_XPath = "//div[@id='search_results']//div[@class='search_results_count']"
URL_of_choosing_LAN_linux_action = "https://store.steampowered.com/search/?tags=19&category3=48&os=linux&filter=topsellers"
first_result_XPath = "//a[@data-ds-appid='4000']"
first_result_title_XPath = "//a[@data-ds-appid='4000']//span[@class='title']"
first_result_date_XPath = "//a[@data-ds-appid='4000']//div[contains(@class,'search_released')]"
first_result_price_XPath = "//a[@data-ds-appid='4000']//div[contains(@class,'search_price  responsive_secondrow')]"
title_inside_XPath = "//div[@id='appHubAppName']"
date_inside_XPath = "//div[@class='date']"
price_inside_XPath = "//div[contains(@class,'game_purchase_price')]"
